### ISSUE TITLE
File::file?() returns true for directories instead of false

### ISSUE THREAD

**Issue by zinga666** [chef-boneyard/win32-file-stat#1]
Hi,

on my Windows Server 2008 R2 machine with

```
C:\>ruby -v
ruby 1.9.3p194 (2012-04-20) [i386-mingw32]
```

and

```
C:\>gem list -l win32
win32-file (0.7.2)
win32-file-stat (1.5.1)
```

I see the following behaviour:

```
irb(main):001:0> File.file?('C:\Windows')
=> false
irb(main):002:0> require 'win32/file'
=> true
irb(main):003:0> File.file?('C:\Windows')
=> true
```

This breaks _FileUtils::cp_r_ and other code.

I filed a bug here because _File::file?_ seems to call _File::Stat#file?_.

I currently work around this issue by monkey patching the _File::Stat_ class with

``` ruby
class File::Stat
  def file?()
    @regular && !@directory
  end
end
```

I wonder why no one else reported this issue before. Could this be related to my setup?!

**Comment by djberg96** [comment]
I think that's a bug. It doesn't manifest itself unless you're running with admin privileges, though, which is probably why most people didn't spot it.

I think the full patch should be @regular && !@directory && !@reparse_point. I'll try to get an updated version out soon.

**Comment by zinga666** [comment]
Ah, I see.

Thanks for the fast reply!

**Comment by djberg96** [comment]
Actually, I wonder if I did this deliberately, because I have a File.file? test for Dir.pwd and check for true. I think there was some debate at some point on whether or not directories should return true or not for File.file? but it seems that that they should not.

**Comment by zinga666** [comment]
Well, Ruby's standard implementation returns _false_ for files. So in my opinion for compatibility reasons your's should too.

Still, I can understand your doubts...

**Comment by djberg96** [comment]
Yep, I'll match the spec. In researching this I also noticed a way to implement File::Stat#socket? as well, so I'll add that into the next release, too. :)

**Comment by zinga666** [comment]
:+1:

**Comment by djberg96** [comment]
Pushed out 1.5.2 today. Thanks for the report!

**Comment by regular** [comment]
Hello, Somebody mentioned my name? ;D

**Comment by djberg96** [comment]
@regular, haha, no, Ruby instance variable name. Sorry about that.
